# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-CD

on:
  push:
    branches:
      - "main"
      - "develop"
      - "release/*"
      - "feat/*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2

    - name: Setup Environment
      run: |
        go mod tidy
        echo "NOW=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: debug step
      run: echo $NOW

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build and push docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/chess-boards:$NOW .
        docker push -t ${{ secrets.DOCKER_HUB_USERNAME }}/chess-boards:$NOW
